# Generated by Django 5.1.2 on 2025-08-28 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(default='TEMP-0000', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='La matrícula solo puede contener letras, números y guiones', regex='^[A-Za-z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El apellido solo puede contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='correo',
            field=models.EmailField(error_messages={'unique': 'Este correo ya está registrado.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener exactamente 8 dígitos numéricos', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')]),
        ),
    ]
