# Generated by Django 5.1.2 on 2025-08-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('estudiantes', '0002_estudiante_matricula_alter_estudiante_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='estudiantes.estudiante'),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('estudiante', 'fecha')},
        ),
    ]
