name: Main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Backend tests
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          python manage.py migrate

      - name: Frontend build
        run: |
          cd frontend
          npm install
          npm run build
